src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Service\ClientIpService;
use App\Validator\Constraints as AppAssert;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Comment entity
 *
 * @AppAssert\CommentIpConstraints
 * @ORM\Entity(repositoryClass="App\Repository\CommentRepository")
 * @ORM\HasLifecycleCallbacks
 * @ORM\Table(name="comments")
 */
class Comment
{
    use DateTimeTrait;

    const COUNT_PARENT_COMMENT = 3;

    /**
     * @var int
     *
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     *
     * @Assert\NotBlank
     * @ORM\Column(name="author", type="string", length=100)
     */
    private $author;

    /**
     * @var string|null
     *
     * @Assert\Email
     * @ORM\Column(name="email", type="string", length=100, nullable=true)
     */
    private $email;

    /**
     * @var string
     *
     * @Assert\NotBlank
     * @ORM\Column(name="comment", type="text")
     */
    private $comment;

    /**
     * @var bool
     *
     * @ORM\Column(name="new", type="boolean")
     */
    private $new = true;

    /**
     * @var bool
     *
     * @ORM\Column(name="active", type="boolean")
     */
    private $active = true;

    /**
     * @var Company
     *
     * @Assert\NotBlank
     * @ORM\ManyToOne(targetEntity="Company", inversedBy="comments")
     * @ORM\JoinColumn(name="company_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $company;

    /**
     * @var Comment|null
     *
     * @ORM\ManyToOne(targetEntity="Comment", inversedBy="children")
     * @ORM\JoinColumn(name="parent_id", referencedColumnName="id", onDelete="CASCADE", nullable=true)
     */
    protected $parent;

    /**
     * @var Collection|Comment[]
     *
     * @ORM\OneToMany(targetEntity="Comment", mappedBy="parent")
     */
    protected $children;

    /**
     * @var Collection|Like[]
     *
     * @ORM\OneToMany(targetEntity="Like", mappedBy="comment")
     */
    protected $likes;

    /**
     * @var string
     *
     * @Assert\NotBlank
     * @ORM\Column(name="ip", type="string", length=25)
     */
    private $ip;

    /**
     * @var int
     *
     * @Assert\Choice({0, 1, 2, 3, 4, 5})
     * @ORM\Column(name="rating", type="integer")
     */
    protected $rating = 0;

    /**
     * @var Collection|Complain[]
     *
     * @ORM\OneToMany(targetEntity="Complain", mappedBy="comment")
     */
    protected $complains;

    /**
     * @throws \Exception
     */
    public function __construct()
    {
        $this->setCreatedAt(new \DateTime());
        $this->children = new ArrayCollection();
        $this->likes = new ArrayCollection();
        $this->complains = new ArrayCollection();
    }

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getAuthor(): ?string
    {
        return $this->author;
    }

    /**
     * @param string $author
     */
    public function setAuthor(string $author): void
    {
        $this->author = $author;
    }

    /**
     * @return string|null
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * @param string|null $email
     */
    public function setEmail(?string $email): void
    {
        $this->email = $email;
    }

    /**
     * @return string|null
     */
    public function getComment(): ?string
    {
        return $this->comment;
    }

    /**
     * @param string $comment
     */
    public function setComment(string $comment): void
    {
        $this->comment = $comment;
    }

    /**
     * @return bool
     */
    public function isNew(): bool
    {
        return $this->new;
    }

    /**
     * @return bool
     */
    public function getNew(): bool
    {
        return $this->new;
    }

    /**
     * @param bool $new
     */
    public function setNew(bool $new): void
    {
        $this->new = $new;
    }

    /**
     * @return Company|null
     */
    public function getCompany(): ?Company
    {
        return $this->company;
    }

    /**
     * @param Company $company
     */
    public function setCompany(Company $company): void
    {
        $this->company = $company;
    }

    /**
     * @return Comment|null
     */
    public function getParent(): ?Comment
    {
        return $this->parent;
    }

    /**
     * @param Comment|null $parent
     */
    public function setParent(?Comment $parent): void
    {
        $this->parent = $parent;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getChildren(): Collection
    {
        return $this->children;
    }

    /**
     * @param Comment $child
     */
    public function addChild(Comment $child): void
    {
        if (!$this->children->contains($child)) {
            $this->children[] = $child;
            $child->setParent($this);
        }
    }

    /**
     * @param Comment $child
     */
    public function removeChild(Comment $child): void
    {
        if ($this->children->contains($child)) {
            $this->children->removeElement($child);
            // set the owning side to null (unless already changed)
            if ($child->getParent() === $this) {
                $child->setParent(null);
            }
        }
    }
    
    /**
     * @return string
     */
    public function __toString(): string
    {
        return $this->getId();
    }

    /**
     * @return int|null
     */
    public function getRating(): ?int
    {
        return $this->rating;
    }

    /**
     * @param int $rating
     */
    public function setRating(int $rating): void
    {
        $this->rating = $rating;
    }

    /**
     * @return Collection|Like[]
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    /**
     * @param Like $like
     */
    public function addLike(Like $like): void
    {
        if (!$this->likes->contains($like)) {
            $this->likes[] = $like;
            $like->setComment($this);
        }
    }

    /**
     * @param Like $like
     */
    public function removeLike(Like $like): void
    {
        if ($this->likes->contains($like)) {
            $this->likes->removeElement($like);
            // set the owning side to null (unless already changed)
            if ($like->getComment() === $this) {
                $like->setComment(null);
            }
        }
    }

    /**
     * @return Collection|Complain[]
     */
    public function getComplains(): Collection
    {
        return $this->complains;
    }

    /**
     * @param Complain $complain
     */
    public function addComplain(Complain $complain): void
    {
        if (!$this->complains->contains($complain)) {
            $this->complains[] = $complain;
            $complain->setComment($this);
        }
    }

    /**
     * @param Complain $complain
     */
    public function removeComplain(Complain $complain): void
    {
        if ($this->complains->contains($complain)) {
            $this->complains->removeElement($complain);
            // set the owning side to null (unless already changed)
            if ($complain->getComment() === $this) {
                $complain->setComment(null);
            }
        }
    }

    /**
     * @return string
     */
    public function getIp(): ?string
    {
        return $this->ip;
    }

    /**
     * @param string $ip
     */
    public function setIp(string $ip): void
    {
        $this->ip = $ip;
    }

    /**
     * @return bool
     */
    public function isDeleted(): bool
    {
        return $this->getCreatedAt()->getTimestamp() + 60 * 60 > time() && $this->getIp() === ClientIpService::getIp();
    }

    /**
     * @return Collection|Like[]
     */
    public function getPositiveLikes(): Collection
    {
        return $this->getLikes()->filter(function (Like $like) {
            return $like->getPositive() === true;
        });
    }

    /**
     * @return Collection|Like[]
     */
    public function getNegativeLikes(): Collection
    {
        return $this->getLikes()->filter(function (Like $like) {
            return $like->getPositive() === false;
        });
    }

    /**
     * @return bool
     */
    public function isActive(): bool
    {
        return $this->active;
    }

    /**
     * @param bool $active
     */
    public function setActive(bool $active): void
    {
        $this->active = $active;
    }

    /**
     * @return bool
     */
    public function getActive(): bool
    {
        return $this->active;
    }

    /**
     * @return string
     */
    public function getCompanyName(): string
    {
        return $this->getCompany()->getName();
    }
}

src/Form/Type/CompanyType.php
<?php

namespace App\Form\Type;

use App\Entity\Company;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichImageType;

/**
 * Company form type
 */
class CompanyType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class)
            ->add('location', TextType::class, [
                'required' => false
            ])
            ->add('logoFile', VichImageType::class, [
                'required' => false
            ])
            ->add('email', EmailType::class)
            ->add('description', TextareaType::class)
            ->add('add', SubmitType::class)
        ;
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Company::class,
        ]);
    }
}

src/Controller/CompanyController.php
<?php

namespace App\Controller;

use App\Entity\Company;
use App\Form\FormErrorForm;
use App\Form\Type\CommentType;
use App\Form\Type\CompanyType;
use App\Form\Type\ComplainType;
use App\Form\Type\LikeType;
use App\Repository\CommentRepository;
use App\Repository\CompanyRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Company Controller
 * @Route("/company")
 */
class CompanyController extends AbstractController
{
    /**
     * @Route("/all", name="companies")
     *
     * @param CompanyRepository $companyRepository
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @return Response
     */
    public function all(
        CompanyRepository $companyRepository,
        PaginatorInterface $paginator,
        Request $request
    ): Response {
        $companiesQuery = $companyRepository->getAllActive();
        $companiesPagination = $paginator->paginate($companiesQuery, $request->get('page', 1));
        $formCompany = $this->createForm(CompanyType::class);

        return $this->render('company/all.html.twig', [
            'companies' => $companiesPagination,
            'formCompany' => $formCompany->createView(),
        ]);
    }

    /**
     * @Route("/add", name="company_add")
     *
     * @param Request $request
     * @param EntityManagerInterface $em
     * @param FormErrorForm $formErrorForm
     * @param SessionInterface $session
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     * @throws \Exception
     */
    public function create(
        Request $request,
        EntityManagerInterface $em,
        FormErrorForm $formErrorForm,
        SessionInterface $session
    ) {
        $company = new Company();

        $formCompany = $this->createForm(CompanyType::class, $company);
        $formCompany->handleRequest($request);

        if ($formCompany->isSubmitted() && $formCompany->isValid()) {
            $em->persist($company);
            $em->flush();
            $session->getFlashBag()->add('messages', 'Company successful created and sent to moderation');
        } else {
            $formErrorForm->setOutputError($formCompany);
        }

        return $this->redirectToRoute('companies');
    }

    /**
     * @Route("/search", name="companies_search")
     *
     * @param CompanyRepository $companyRepository
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @return Response
     */
    public function search(
        CompanyRepository $companyRepository,
        PaginatorInterface $paginator,
        Request $request
    ): Response {
        $search = $request->get('search');
        if ($search === null || ($search !== null && strlen($search) < 3)) {
            throw $this->createNotFoundException('Page not exists');
        }

        $companiesQuery = $companyRepository->search($search);
        $companiesPagination = $paginator->paginate($companiesQuery, $request->get('page', 1));
        $formCompany = $this->createForm(CompanyType::class);

        return $this->render('company/search.html.twig', [
            'companies' => $companiesPagination,
            'formCompany' => $formCompany->createView()
        ]);
    }

    /**
     * @Route("/{id}", name="company_one")
     *
     * @param Company $company
     * @param CommentRepository $commentRepository
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @return Response
     * @throws \Exception
     */
    public function view(
        Company $company,
        CommentRepository $commentRepository,
        PaginatorInterface $paginator,
        Request $request
    ): Response {
        $commentQuery = $commentRepository->getCommentFirstLevelByCompany($company);
        $commentPagination = $paginator->paginate($commentQuery, $request->get('page', 1));

        $formComment = $this->createForm(CommentType::class)->createView();
        $formLike = $this->createForm(LikeType::class)->createView();
        $formComplain = $this->createForm(ComplainType::class);

        return $this->render('company/view.html.twig', [
            'company' => $company,
            'comments' => $commentPagination,
            'formComment' => $formComment,
            'formLike' => $formLike,
            'formComplain' => $formComplain->createView()
        ]);
    }
}

templates/company/all.html.twig
{% extends 'base.html.twig' %}

{% block title %}Companies - The Comments{% endblock %}

{% block body %}
    <div>
        <h1 class="mt-5">Companies</h1>
        {% set errors = app.session.flashbag.get('formErrors') %}
        {% if errors | length %}
            {% for flashMessage in errors %}
                <p class="alert-warning">{{ flashMessage }}</p>
            {% endfor %}
        {% endif %}

        {% set messages = app.session.flashbag.get('messages') %}
        {% if messages | length %}
            {% for flashMessage in messages %}
                <p class="alert-success">{{ flashMessage }}</p>
            {% endfor %}
        {% endif %}

        {% for company in companies %}
            <p style="font-size: 35px" class="mt-5">
                {% if company.logo %}
                    <img src="{{ vich_uploader_asset(company, 'logoFile') }}"/>
                {% endif %}  
                <a href="{{ path('company_one', { 'id' : company.id }) }}">
                    {{ company.name }}
                </a>
            </p>
            <p>
                {% set rating = company.rating | round %}
                {% for i in range(1, rating) %}
                    <i class="fa fa-star"></i>
                {% endfor %}
                {{ company.rating }}
            </p>
            <p class="lead"> {{ company.description }}</p>
            <p>{{ company.location }}</p>
        {% endfor %}

        <h2>Add company</h2>
        {{ form(formCompany, {'method': 'POST', 'action': path('company_add')}) }}

        {{ knp_pagination_render(companies) }}
    </div>
{% endblock %}

templates/company/search.html.twig
{% extends 'base.html.twig' %}

{% block title %}Search - The Comments{% endblock %}

{% block body %}
    <div>
        <h1 class="mt-5">Search "{{ app.request.get('search') }}"</h1>
        {% set errors = app.session.flashbag.get('formErrors') %}

        {% for company in companies %}
            <p style="font-size: 35px" class="mt-5">
                {% if company.logo %}
                    <img src="{{ vich_uploader_asset(company, 'logoFile') }}"/>
                {% endif %}  
                <a href="{{ path('company_one', { 'id' : company.id }) }}">
                    {{ company.name }}
                </a>
            </p>
            <p>
                {% set rating = company.rating | round %}
                {% for i in range(1, rating) %}
                    <i class="fa fa-star"></i>
                {% endfor %}
                {{ company.rating }}
            </p>
            <p class="lead"> {{ company.description }}</p>
            <p>{{ company.location }}</p>
        {% endfor %}


        {{ knp_pagination_render(companies) }}
    </div>
{% endblock %}

templates/company/view.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ company.name }} - Company - The Comments{% endblock %}

{% block body %}
<div>
    <h1>{{ company.name }}</h1>
    <p>
        {% set rating = company.rating | round %}
        {% for i in range(1, rating) %}
            <i class="fa fa-star"></i>
        {% endfor %}
        {{ company.rating }}
    </p>
    <div>
        Location: {{ company.location }}
    </div>
    <div>
        Description: {{ company.description }}
    </div>
    <h2>Comments:</h2>
    {% set errors = app.session.flashbag.get('formErrors') %}
    {% if errors | length %}
        {% for flashMessage in errors %}
            <p class="alert-warning">{{ flashMessage }}</p>
        {% endfor %}
    {% endif %}

    {% set messages = app.session.flashbag.get('messages') %}
    {% if messages | length %}
        {% for flashMessage in messages %}
            <p class="alert-success">{{ flashMessage }}</p>
        {% endfor %}
    {% endif %}

    <a class="add-comment" href="{{ path('comment_add', { 'id': company.id }) }}"> Add </a>
    <div class="comment-container"></div>
    <ul>
        {% for comment in comments %}
            <li>
                Author {{ comment.author }}
                {% set rating = comment.rating | round %}
                {% for i in range(1, rating) %}
                    <i class="fa fa-star"></i>
                {% endfor %}
                {{ comment.rating }}
                <br />
                {{ comment.comment }}
                <br />
                Date: {{ comment.createdAt | date("Y-m-d") }}
                <br />
                Likes:
                <a class="add-like" href="{{ path('like_create', { 'id' : comment.id }) }}" data-like="1">+</a>
                {{ comment.positiveLikes | length }}
                |
                <a class="add-like" href="{{ path('like_create', { 'id' : comment.id }) }}" data-like="0">-</a>
                {{ comment.negativeLikes | length }}
                <br />
                {% if comment.isDeleted() %}
                    <a href="{{ path('comment_delete', { 'id': comment.id }) }}">Delete</a>
                {% endif %}
                <br />
                <a class="add-complain" href="{{ path('complain_create', { 'id': comment.id }) }}"> Complain </a>
                <div class="complain-container"></div>
                {% if comment.children %}
                    <ul>
                        {% for child in comment.children %}
                            <li>
                                Author {{ child.author }}
                                {% set rating = child.rating | round %}
                                {% for i in range(1, rating) %}
                                    <i class="fa fa-star"></i>
                                {% endfor %}
                                {{ child.rating }}
                                <br />
                                {{ child.comment }}
                                <br />
                                Date: {{ child.createdAt | date("Y-m-d") }}
                                <br />
                                Likes:
                                <a class="add-like" href="{{ path('like_create', { 'id' : child.id }) }}" data-like="1">+</a>
                                {{ child.positiveLikes | length }}
                                |
                                <a class="add-like" href="{{ path('like_create', { 'id' : child.id }) }}" data-like="0">-</a>
                                {{ child.negativeLikes | length }}
                                <br />
                                {% if child.isDeleted() %}
                                    <a href="{{ path('comment_delete', { 'id': child.id }) }}">Delete</a>
                                {% endif %}
                                <br />
                                <a class="add-complain" href="{{ path('complain_create', { 'id': comment.id }) }}"> Complain </a>
                                <div class="complain-container"></div>
                            </li>
                        {% endfor %}
                    </ul>
                {% endif %}
                <a class="add-comment" href="{{ path('comment_add_child', { 'id': company.id, 'comment_id': comment.id }) }}"> Replay </a>
                <div class="comment-container"></div>
                <br />
                <br />
            </li>
        {% endfor %}
    </ul>
    <div id="comment" style="display: none">{{ form(formComment, {'method': 'POST'}) }}</div>
    <div id="complain" style="display: none">{{ form(formComplain, {'method': 'POST'}) }}</div>
    <div id="like" style="display: none">{{ form(formLike, {'method': 'POST'}) }}</div>
    {{ knp_pagination_render(comments) }}
</div>
{% endblock %}

{% block javascripts %}
    <script type="text/javascript">
        $(document).ready(function() {
            $('.add-comment').on('click', function (e) {
                e.preventDefault();
                $('form[name=comment]').attr('action', $(this).attr('href'));
                $('.comment-container').empty();
                $(this).next('.comment-container').html($('#comment').html());
            })
            $('.add-complain').on('click', function (e) {
                e.preventDefault();
                $('form[name=complain]').attr('action', $(this).attr('href'));
                $('.complain-container').empty();
                $(this).next('.complain-container').html($('#complain').html());
            })

            $('.add-like').on('click', function (e) {
                e.preventDefault();
                $('form[name=like]').attr('action', $(this).attr('href'));
                $('#like_positive').val($(this).data('like'));
                $('form[name=like]').submit();
            })
        })
    </script>
{% endblock %}